'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { 
  ShieldCheck, Zap, Lock, Globe, Menu, X, Terminal, CheckCircle2, ChevronRight 
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

type Language = 'en' | 'ru';

const translations = {
  en: {
    heroTitle: 'Secure Smart Contracts with ',
    heroTitleHighlight: 'AI-Powered Audits',
    heroSubtitle: 'Detect and fix vulnerabilities in Solidity, Rust, and Move instantly. Enterprise-grade security for the decentralized web.',
    startAudit: 'Start Free Audit',
    learnMore: 'How It Works',
    login: 'Log In',
    features: {
      upload: { title: 'Upload Code', desc: 'Drag & drop Solidity, Rust, or Move files into our secure enclave.' },
      analyze: { title: 'AI Analysis', desc: 'Deep scanning for reentrancy, overflows, and logic flaws in seconds.' },
      fix: { title: 'Auto-Remediation', desc: 'Get instant code fixes generated by our specialized LLM engine.' }
    },
    stats: {
      secure: 'Secure',
      speed: 'Fast',
      engine: 'AI Engine'
    }
  },
  ru: {
    heroTitle: 'Защита смарт-контрактов через ',
    heroTitleHighlight: 'ИИ-Аудит',
    heroSubtitle: 'Находите и исправляйте уязвимости в Solidity, Rust и Move мгновенно. Безопасность корпоративного уровня для Web3.',
    startAudit: 'Начать аудит',
    learnMore: 'Как это работает',
    login: 'Войти',
    features: {
      upload: { title: 'Загрузка кода', desc: 'Перетащите файлы Solidity, Rust или Move в наш защищенный контур.' },
      analyze: { title: 'ИИ Анализ', desc: 'Глубокое сканирование на реентранси, переполнения и логические баги.' },
      fix: { title: 'Авто-исправление', desc: 'Получайте готовый исправленный код, сгенерированный нашим LLM.' }
    },
    stats: {
      secure: 'Надежно',
      speed: 'Быстро',
      engine: 'ИИ Движок'
    }
  },
};

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const [language, setLanguage] = useState<Language>('en');
  const [isLangMenuOpen, setIsLangMenuOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  
  const { scrollY } = useScroll();
  const y1 = useTransform(scrollY, [0, 500], [0, 200]);
  const y2 = useTransform(scrollY, [0, 500], [0, -150]);

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      setMousePosition({ x: e.clientX, y: e.clientY });
    };
    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language | null;
    if (savedLang === 'ru' || savedLang === 'en') {
      setLanguage(savedLang);
    } else {
      const browserLang = navigator.language.startsWith('ru') ? 'ru' : 'en';
      setLanguage(browserLang);
    }
    setMounted(true);
  }, []);

  const t = translations[language];

  const toggleLang = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    setIsLangMenuOpen(false);
  };

  if (!mounted) return null;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-blue-950 to-slate-950 text-slate-200 selection:bg-blue-500/30 overflow-x-hidden font-sans">
      
      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
        <div 
          className="absolute w-96 h-96 bg-blue-500/20 rounded-full blur-3xl transition-all duration-1000 ease-out"
          style={{ left: `${mousePosition.x * 0.02}px`, top: `${mousePosition.y * 0.02}px` }}
        />
        <div 
          className="absolute w-96 h-96 bg-purple-500/20 rounded-full blur-3xl transition-all duration-1000 ease-out"
          style={{ right: `${mousePosition.x * 0.01}px`, bottom: `${mousePosition.y * 0.01}px` }}
        />
        <div className="absolute top-20 right-20 w-64 h-64 bg-cyan-500/10 rounded-full blur-3xl animate-pulse" />
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:50px_50px] [mask-image:radial-gradient(ellipse_80%_50%_at_50%_50%,black,transparent)]" />
      </div>

      <nav className="fixed top-0 w-full z-50 border-b border-white/5 bg-slate-950/70 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-blue-600 to-purple-600 rounded-xl flex items-center justify-center shadow-lg shadow-blue-500/20">
              <ShieldCheck className="w-6 h-6 text-white" />
            </div>
            <span className="text-xl font-bold text-white tracking-tight">Clapy.ai</span>
          </div>

          <div className="hidden md:flex items-center gap-6">
            <div className="relative">
              <button 
                onClick={() => setIsLangMenuOpen(!isLangMenuOpen)}
                className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors bg-white/5 px-3 py-1.5 rounded-lg border border-white/5 hover:bg-white/10"
              >
                <Globe className="w-4 h-4" />
                <span className="uppercase font-medium">{language}</span>
              </button>
              
              {isLangMenuOpen && (
                <div className="absolute top-full right-0 mt-2 w-32 bg-slate-900 border border-slate-700 rounded-xl shadow-xl overflow-hidden backdrop-blur-xl">
                  <button onClick={() => toggleLang('en')} className="w-full text-left px-4 py-3 text-sm hover:bg-white/5 text-slate-300 hover:text-white transition-colors">English</button>
                  <button onClick={() => toggleLang('ru')} className="w-full text-left px-4 py-3 text-sm hover:bg-white/5 text-slate-300 hover:text-white transition-colors">Русский</button>
                </div>
              )}
            </div>

            <div className="h-6 w-px bg-white/10" />

            <Link href="/login" className="text-sm font-medium text-slate-300 hover:text-white transition-colors">
              {t.login}
            </Link>
            
            <Link href="/register">
              <Button className="bg-white text-black hover:bg-slate-200 border-0 rounded-full px-6 font-semibold shadow-lg shadow-white/10 transition-transform hover:scale-105">
                Get Started
              </Button>
            </Link>
          </div>

          <button className="md:hidden text-white p-2 rounded-lg hover:bg-white/5" onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>
            {mobileMenuOpen ? <X /> : <Menu />}
          </button>
        </div>

        {mobileMenuOpen && (
          <div className="md:hidden absolute top-20 left-0 w-full bg-slate-950 border-b border-white/10 p-6 flex flex-col gap-4 shadow-2xl backdrop-blur-xl">
             <Link href="/login" className="text-lg font-medium text-slate-300 p-2 hover:bg-white/5 rounded-lg">Log In</Link>
             <Link href="/register" className="text-lg font-medium text-blue-400 p-2 hover:bg-blue-500/10 rounded-lg">Get Started</Link>
             <div className="flex gap-4 mt-4 border-t border-white/10 pt-4">
               <button onClick={() => toggleLang('en')} className={cn("text-sm px-4 py-2 rounded-lg", language === 'en' ? "bg-white/10 text-white" : "text-slate-500")}>EN</button>
               <button onClick={() => toggleLang('ru')} className={cn("text-sm px-4 py-2 rounded-lg", language === 'ru' ? "bg-white/10 text-white" : "text-slate-500")}>RU</button>
             </div>
          </div>
        )}
      </nav>

      <main className="relative z-10 pt-32 pb-20 px-6">
        <div className="max-w-7xl mx-auto text-center">
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-sm font-medium mb-8 shadow-[0_0_15px_rgba(59,130,246,0.2)]"
          >
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
            </span>
            v2.0 Now Live with Rust Support
          </motion.div>

          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-5xl md:text-7xl font-bold text-white leading-[1.1] tracking-tight mb-6"
          >
            {t.heroTitle}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-400 to-blue-400 animate-gradient-x pb-2">
              {t.heroTitleHighlight}
            </span>
          </motion.h1>

          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed"
          >
            {t.heroSubtitle}
          </motion.p>

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link href="/login">
              <Button className="h-14 px-8 text-lg bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 text-white border-0 shadow-[0_0_30px_rgba(59,130,246,0.4)] rounded-full transition-all hover:scale-105 font-bold">
                <Zap className="w-5 h-5 mr-2 fill-white" /> {t.startAudit}
              </Button>
            </Link>
            <Button 
              onClick={() => document.getElementById('how-it-works')?.scrollIntoView({ behavior: 'smooth' })}
              variant="outline" 
              className="h-14 px-8 text-lg bg-white/5 border-white/10 text-white hover:bg-white/10 rounded-full backdrop-blur-sm transition-all hover:border-white/20"
            >
              {t.learnMore}
            </Button>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.5, duration: 0.8 }}
            className="mt-24 relative mx-auto max-w-4xl group"
          >
            <div className="absolute -inset-1 bg-gradient-to-r from-blue-500 to-purple-600 rounded-3xl blur-xl opacity-20 group-hover:opacity-30 transition-opacity duration-1000"></div>
            <div className="relative bg-slate-950/80 border border-white/10 rounded-3xl overflow-hidden shadow-2xl backdrop-blur-xl">
              <div className="flex items-center gap-2 px-6 py-4 bg-white/5 border-b border-white/5">
                <div className="flex gap-2">
                  <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500/50"></div>
                  <div className="w-3 h-3 rounded-full bg-yellow-500/20 border border-yellow-500/50"></div>
                  <div className="w-3 h-3 rounded-full bg-green-500/20 border border-green-500/50"></div>
                </div>
                <div className="ml-4 px-3 py-1 rounded-md bg-black/40 text-xs text-slate-400 font-mono border border-white/5">scan_report.json</div>
              </div>
              <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-10 text-left">
                <div className="space-y-3 font-mono text-sm leading-relaxed">
                  <div className="text-slate-500">// Vulnerability Detected</div>
                  <div className="text-purple-400 font-bold">function withdraw() public {'{'}</div>
                  <div className="pl-4 py-1 text-red-400 border-l-2 border-red-500/50 bg-red-500/10 rounded-r">
                    (bool success, ) = msg.sender.call{'{'}value: amount{'}'}("");
                  </div>
                  <div className="pl-4 text-slate-300">require(success, "Transfer failed");</div>
                  <div className="pl-4 py-1 text-red-400 border-l-2 border-red-500/50 bg-red-500/10 rounded-r">
                    balances[msg.sender] = 0; <span className="text-red-300/70 text-xs ml-2">// &lt;- Reentrancy Risk</span>
                  </div>
                  <div className="text-purple-400 font-bold">{'}'}</div>
                </div>

                <div className="space-y-4">
                  <div className="flex items-center gap-4 p-4 rounded-xl bg-red-500/10 border border-red-500/20 shadow-inner shadow-red-500/5">
                    <div className="p-2.5 bg-red-500/20 rounded-lg text-red-400 shadow-lg shadow-red-500/10"><Lock className="w-5 h-5" /></div>
                    <div>
                      <div className="text-sm font-bold text-red-400">Critical Severity</div>
                      <div className="text-xs text-red-300/70 mt-0.5">Reentrancy Attack Vector Detected</div>
                    </div>
                  </div>
                  <div className="flex items-center gap-4 p-4 rounded-xl bg-green-500/10 border border-green-500/20 shadow-inner shadow-green-500/5">
                    <div className="p-2.5 bg-green-500/20 rounded-lg text-green-400 shadow-lg shadow-green-500/10"><Terminal className="w-5 h-5" /></div>
                    <div>
                      <div className="text-sm font-bold text-green-400">AI Fix Generated</div>
                      <div className="text-xs text-green-300/70 mt-0.5">Check-Effects-Interactions Pattern Applied</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>

        </div>
      </main>

      <section id="how-it-works" className="py-32 relative z-10">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-20">
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">Enterprise-Grade Pipeline</h2>
            <p className="text-slate-400 max-w-2xl mx-auto text-lg">
              From code upload to automated remediation, our pipeline ensures zero-day protection with military-grade precision.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            
            <div className="group bg-white/5 border border-white/10 p-8 rounded-3xl hover:bg-white/10 hover:border-blue-500/30 transition-all duration-300 hover:-translate-y-1 backdrop-blur-sm">
              <div className="w-16 h-16 bg-blue-500/10 rounded-2xl flex items-center justify-center mb-6 border border-blue-500/20 group-hover:scale-110 transition-transform shadow-[0_0_20px_rgba(59,130,246,0.15)]">
                <span className="font-mono text-2xl font-bold text-blue-400">01</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-3 group-hover:text-blue-200 transition-colors">{t.features.upload.title}</h3>
              <p className="text-slate-400 leading-relaxed">{t.features.upload.desc}</p>
            </div>

            <div className="group bg-white/5 border border-white/10 p-8 rounded-3xl hover:bg-white/10 hover:border-purple-500/30 transition-all duration-300 hover:-translate-y-1 backdrop-blur-sm">
              <div className="w-16 h-16 bg-purple-500/10 rounded-2xl flex items-center justify-center mb-6 border border-purple-500/20 group-hover:scale-110 transition-transform shadow-[0_0_20px_rgba(168,85,247,0.15)]">
                <span className="font-mono text-2xl font-bold text-purple-400">02</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-3 group-hover:text-purple-200 transition-colors">{t.features.analyze.title}</h3>
              <p className="text-slate-400 leading-relaxed">{t.features.analyze.desc}</p>
            </div>

            <div className="group bg-white/5 border border-white/10 p-8 rounded-3xl hover:bg-white/10 hover:border-green-500/30 transition-all duration-300 hover:-translate-y-1 backdrop-blur-sm">
              <div className="w-16 h-16 bg-green-500/10 rounded-2xl flex items-center justify-center mb-6 border border-green-500/20 group-hover:scale-110 transition-transform shadow-[0_0_20px_rgba(34,197,94,0.15)]">
                <span className="font-mono text-2xl font-bold text-green-400">03</span>
              </div>
              <h3 className="text-xl font-bold text-white mb-3 group-hover:text-green-200 transition-colors">{t.features.fix.title}</h3>
              <p className="text-slate-400 leading-relaxed">{t.features.fix.desc}</p>
            </div>

          </div>
        </div>
      </section>

      <div className="border-y border-white/10 bg-slate-950/50 backdrop-blur-md py-16 relative z-10">
         <div className="max-w-6xl mx-auto px-6 flex flex-wrap justify-center gap-16 md:justify-around items-center">
            <div className="flex items-center gap-5 group">
               <div className="p-4 bg-blue-500/10 rounded-2xl text-blue-400 border border-blue-500/20 group-hover:scale-110 transition-transform duration-300"><ShieldCheck className="w-8 h-8" /></div>
               <div>
                  <div className="text-3xl font-bold text-white mb-1">100%</div>
                  <div className="text-xs text-blue-300 uppercase tracking-widest font-semibold">{t.stats.secure}</div>
               </div>
            </div>
            <div className="h-16 w-px bg-white/10 hidden md:block" />
            <div className="flex items-center gap-5 group">
               <div className="p-4 bg-purple-500/10 rounded-2xl text-purple-400 border border-purple-500/20 group-hover:scale-110 transition-transform duration-300"><Zap className="w-8 h-8" /></div>
               <div>
                  <div className="text-3xl font-bold text-white mb-1">&lt; 60s</div>
                  <div className="text-xs text-purple-300 uppercase tracking-widest font-semibold">{t.stats.speed}</div>
               </div>
            </div>
            <div className="h-16 w-px bg-white/10 hidden md:block" />
            <div className="flex items-center gap-5 group">
               <div className="p-4 bg-green-500/10 rounded-2xl text-green-400 border border-green-500/20 group-hover:scale-110 transition-transform duration-300"><Terminal className="w-8 h-8" /></div>
               <div>
                  <div className="text-3xl font-bold text-white mb-1">GPT-4o</div>
                  <div className="text-xs text-green-300 uppercase tracking-widest font-semibold">{t.stats.engine}</div>
               </div>
            </div>
         </div>
      </div>

      <footer className="py-12 text-center text-slate-500 text-sm relative z-10 bg-slate-950 border-t border-white/5">
        <div className="flex items-center justify-center gap-2 mb-4 opacity-50 hover:opacity-100 transition-opacity">
            <div className="w-6 h-6 bg-gradient-to-br from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
              <ShieldCheck className="w-3 h-3 text-white" />
            </div>
            <span className="text-lg font-bold text-white tracking-tight">Clapy.ai</span>
        </div>
        <p>&copy; {new Date().getFullYear()} Clapy.ai. Securing the decentralized future.</p>
      </footer>
    </div>
  );
}